---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Alpine
    apk:
      name: 
        - apache2
        - php83
        - php83-apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Alpine"

  - name: install apache and php packages for CentOS
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

