---

- hosts: all
  become: true
  tasks:

  - name: updated repository index
    apk:
      update_cache: yes

  - name: install apache2 package
    apk:
      name: apache2
      state: absent

  - name: add php support for apache
    apk:
      name: php7
      state: absent 
